{{ config(materialized='view') }}

with source_data as (
    select * from {{ source('public', 'raw_messages') }}
)

select
    message_id,
    channel_name,
    -- Match the precise column generated by your python ingestion engine
    message_date,
    message_text,
    views,
    forwards,
    has_media
from source_data